AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/*.short*.rb'

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/ruby-1.8*.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
