AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/*.short*.rb'

Metrics/BlockLength:
  Exclude:
    - '**/Rakefile'

Naming/FileName:
  Exclude:
    - '**/ruby-1.8*.rb'
    - '**/ruby-1.9*.rb'
    - '**/ruby-2.5*.rb'

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/ruby-1.8*.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
